all:
  hosts:
    er01:
      ansible_connection: network_cli
      ansible_host: 192.168.1.1
      ansible_network_os: edgeos
      wan_interface: "eth0"

      client_private_ip: "192.168.141.2/24"
      server_publickey: "kjsJKhasdiuyIOU823ask2KLJhawd8fy23lkjahdf4E="
      server_public_ip: "34.200.241.65"
      ipsec_psk: "478KJhasdkfjhw8234MNasd"
      ipsec_username: "remoteuser"
      ipsec_user_pass: "2348957KLJhwsmnavergAqiueN"
      client_ip_pool_start: "192.168.140.10"
      client_ip_pool_stop: "192.168.140.200"
      ext_dns1: "1.1.1.1"
      ext_dns2: "208.67.222.222"