base_role=
    mgmt_ip=192.168.1.1
    hostname=er01
    domain=oldsmail.me
    wan_port=eth4
    lan_port=eth0
upgrade_firmware_role=
    firmware_file='ER-e50.v1.10.0.5056246.tar'
admin_user_role=
    username=jamesolds
    #password_hash is generated by mkpasswd -m sha-512
    password_hash='$6$IvLvSWBz84x8cJS$VQfr1HlywooXjS3kldX7VZZ9kpwE.7IEC8xihYAsr2vypA0swTXL1aFH9AHUV6SHiCRC2H8A1u6HoBdZSmB45/'
    ssh_private_key=~/.ssh/er01
    ssh_public_key=~/.ssh/er01.pub
ddns_role=
    ddns_service=
    ddns_host=
    ddns_username=
    ddns_password=
letsencrypt_role=

ipsec_server_role=
    ipsec_username=
    ipsec_user_pass=
    ipsec_psk=
    client_ip_pool_start=192.168.99.10
    client_ip_pool_stop=192.168.99.250