all:
  hosts:
    er01:
      ansible_connection: network_cli
      ansible_host: 192.168.1.1
      ansible_network_os: edgeos
      wan_interface: "eth0"
      wan_ip: "75.55.241.162"
      bgp_asn: "65000"

      # AWS tunnel configuration from terraform/dev/vpc output
      tunnel1_address: "34.202.178.183"
      tunnel1_bgp_asn: "64512"
      tunnel1_bgp_holdtime: "30"
      tunnel1_cgw_inside_address: "169.254.45.202"
      tunnel1_preshared_key: "NQ..oqmc14mykx63bRp0p079jTnvKrH."
      tunnel1_vgw_inside_address: "169.254.45.201"
      tunnel2_address: "54.174.66.142"
      tunnel2_bgp_asn: "64512"
      tunnel2_bgp_holdtime: "30"
      tunnel2_cgw_inside_address: "169.254.45.134"
      tunnel2_preshared_key: "YsZA_l74zY6Z5cY9vC14wBQlzI2LFlPx"
      tunnel2_vgw_inside_address: "169.254.45.133"